<?php

namespace App\Console\Commands;

use App\Models\Employee;
use App\Services\PayrollService;
use Carbon\Carbon;
use Illuminate\Console\Command;

/**
 * Artisan command for scheduled / manual payroll generation.
 *
 * Usage:
 *   php artisan payroll:generate --frequency=weekly
 *   php artisan payroll:generate --frequency=monthly --start=2026-05-01 --end=2026-05-31
 *
 * Schedule in routes/console.php:
 *   Schedule::command('payroll:generate --frequency=weekly')->weekly()->mondays()->at('00:01');
 *   Schedule::command('payroll:generate --frequency=monthly')->monthlyOn(1, '00:01');
 */
class GeneratePayrollCommand extends Command
{
    protected $signature = 'payroll:generate
                            {--frequency=weekly : weekly | semi_monthly | monthly}
                            {--start=           : Start date YYYY-MM-DD (defaults to period start)}
                            {--end=             : End date YYYY-MM-DD   (defaults to period end)}
                            {--dry-run          : Preview without saving}';

    protected $description = 'Generate a payroll period for all active employees';

    public function __construct(private PayrollService $service)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $frequency = $this->option('frequency');
        $isDryRun  = $this->option('dry-run');

        // ── Resolve date range ────────────────────────────────────────────────
        [$startDate, $endDate] = $this->resolveDateRange($frequency);

        $this->info("Payroll generation — {$frequency}");
        $this->line("Period : {$startDate} → {$endDate}");
        $this->line("Employees: " . Employee::where('status', 'Active')->count() . " active");

        if ($isDryRun) {
            $this->warn("[DRY RUN] No data written. Remove --dry-run to execute.");
            return Command::SUCCESS;
        }

        // ── Find a system employee to attribute the run to ────────────────────
        $admin = Employee::whereIn('role', ['Admin', 'Manager'])->first();
        if (!$admin) {
            $this->error("No Manager or Admin employee found to attribute payroll run.");
            return Command::FAILURE;
        }

        try {
            $period = $this->service->generate(
                startDate:   $startDate,
                endDate:     $endDate,
                frequency:   $frequency,
                generatedBy: $admin->id,
                notes:       "Auto-generated by artisan payroll:generate",
            );

            $this->newLine();
            $this->info("✔ Payroll generated successfully.");
            $this->table(
                ['Period ID', 'Label', 'Entries', 'Total Gross'],
                [[
                    $period->id,
                    $period->label,
                    $period->entry_count,
                    '₱' . number_format($period->total_gross, 2),
                ]]
            );

            return Command::SUCCESS;

        } catch (\RuntimeException $e) {
            $this->error("✘ {$e->getMessage()}");
            return Command::FAILURE;
        }
    }

    /**
     * Resolve start/end dates for the given frequency,
     * defaulting to the most recently completed period.
     */
    private function resolveDateRange(string $frequency): array
    {
        if ($this->option('start') && $this->option('end')) {
            return [$this->option('start'), $this->option('end')];
        }

        $now = Carbon::now();

        return match ($frequency) {
            'weekly' => [
                $now->copy()->subWeek()->startOfWeek()->toDateString(),
                $now->copy()->subWeek()->endOfWeek()->toDateString(),
            ],
            'semi_monthly' => $now->day <= 15
                ? [
                    $now->copy()->subMonth()->setDay(16)->toDateString(),
                    $now->copy()->subMonth()->endOfMonth()->toDateString(),
                ]
                : [
                    $now->copy()->startOfMonth()->toDateString(),
                    $now->copy()->setDay(15)->toDateString(),
                ],
            'monthly' => [
                $now->copy()->subMonth()->startOfMonth()->toDateString(),
                $now->copy()->subMonth()->endOfMonth()->toDateString(),
            ],
            default => throw new \InvalidArgumentException("Unknown frequency: {$frequency}"),
        };
    }
}